Views/CBVs/urls.py
from django.urls import path
from .import views

app_name='CBVs'

urlpatterns=[
      path('',views.PostsListView.as_view(),name='list'),
      path('<int:pk>/',views.PostsDetailView.as_view(),name='detail'),
      path('update/<int:pk>/',views.PostsUpdateView.as_view(),name='update'),
      path('create/',views.PostsCreateView.as_view(),name='create'),
      path('delete/<int:pk>/',views.PostsDeleteView.as_view(),name='delete'),
]

Views/Views/urls.py
from django.contrib import admin
from django.urls import path,include
from CBVs import views
urlpatterns = [
    path('admin/', admin.site.urls,name='admin'),
    path('',views.IndexView.as_view(),name='index'),
    path('CBVs/',include('CBVs.urls',namespace='CBVs')),

]

Views/CBVs/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
class PostsManager(models.Manager):
    def create_post(self,post_title,post_author):
        post=self.create(post_title=post_title,post_author=post_author)
        return post

def upload_post_image(instance,filename):
    return "media/{post_title}/{filename}/".format(post_title=instance.post_title,filename=filename)



class Posts(models.Model):
    post_title=models.CharField(max_length=300)
    post_image=models.ImageField(upload_to=upload_post_image,blank=True,null=True)
    post_content=models.TextField(blank=True)
    post_date=models.DateTimeField(auto_now_add=True)
    post_author=models.ForeignKey(User,on_delete=models.CASCADE)
    objects=PostsManager()

    def __str__(self):
        return self.post_title

    def get_absolute_url(self):
        return reverse("CBVs:detail",kwargs={'pk':self.pk})


    @classmethod
    def create_post(cls,post_title,post_author):
        post=cls(post_title=post_title,post_author=post_author)

        return post

Views/CBVs/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.http import HttpResponse
from django.views.generic import (View,TemplateView,
                                ListView,DetailView,
                                CreateView,DeleteView,
                                UpdateView)
from . import models
# Create your views here.

# Original Function View:
#
# def index(request):
#     return render(request,'index.html')
#
#

# Pretty simple right?
class IndexView(TemplateView):
    # Just set this Class Object Attribute to the template page.
    # template_name = 'app_name/site.html'
    template_name = 'index.html'

    # def get_context_data(self,**kwargs):
    #     context  = super().get_context_data(**kwargs)
    #     context['injectme'] = "Basic Injection!"
    #     return context

class PostsListView(ListView):
    # If you don't pass in this attribute,
    # Django will auto create a context name
    # for you with object_list!
    # Default would be 'school_list'

    # Example of making your own:
    # context_object_name = 'schools'
    template_name='index.html'
    model=models.Posts



class PostsDetailView(DetailView):
    context_object_name = 'posts_details'
    model = models.Posts
    template_name = 'CBVs/posts_detail.html'


class PostsCreateView(CreateView):
    

    fields = '__all__'
    model = models.Posts


class PostsUpdateView(UpdateView):
    fields = '__all__'
    model = models.Posts

class PostsDeleteView(DeleteView):
    model = models.Posts
    success_url = reverse_lazy("CBVs:list")

Views/CBVs/templates/CBVs/posts_confirm_delete.html
{% extends "base.html" %}

{% block body %}

<div class="jumbotron">
  <h1>Delete :: {{posts.post_title }}?</h1>

  <form method="post">
    {% csrf_token %}
    <input type="submit" class="btn btn-danger" value="Delete">
    <a href="{% url 'CBVs:detail' pk=posts.pk%} "><input type="button" class="btn btn-primary" value="Cancel"></a>

  </form>
</div>


{% endblock %}

Views/CBVs/templates/CBVs/posts_detail.html
{% extends "base.html" %}
{% block body %}
  <div class="jumbotron">
    <h1>Welcome to the Post Detail Page</h1>
    <h2>Post Details:</h2>
    <!-- <p>Id_num: {{school_details.id}}</p> -->
    <p>Title: {{posts_details.post_title}}</p>
    <p>Content: {{posts_details.post_content}}</p>
    <p>Image: {{posts_details.post_image}}</p>
    <p>Date: {{posts_details.post_date}}</p>
    <p>Posted By: {{posts_details.post_author}}</p>

  </div>
  <div class="container">
    <p><a class='btn btn-warning' href="{% url 'CBVs:update' pk=posts_details.pk %}">Update</a></p>


  </div>

{% endblock %}

Views/CBVs/templates/CBVs/posts_form.html
{% extends "base.html" %}

{% block body %}

<div class="jumbotron">
  <h1>
    {% if not form.instance.pk %}
    Create Post
    {% else %}
    Update Post
    {% endif %}
  </h1>
    <form method="POST">
      {% csrf_token %}
      {{ form.as_p }}
      <input type="submit" class='btn btn-primary' value="Submit">

    </form>

</div>


{% endblock %}

Views/templates/base.html
{% load static %}


<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>{% block title %}{% endblock %}</title>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>


  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="{% url 'CBVs:list' %}">Home</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <!-- <a class="nav-link" href="{% url 'CBVs:list' %}">Posts<span class="sr-only">(current)</span></a> -->
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'CBVs:create' %}">Create Post</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Dropdown
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <a class="dropdown-item" href="#">Action</a>
            <a class="dropdown-item" href="#">Another action</a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="#">Something else here</a>
          </div>
        </li>
        <li class="nav-item">
            <li><a class="nav-link" href="{% url 'admin:index' %}">Admin</a></li>
            <!-- <li><a class="nav-link" href="posts_confirm_delete.html">Delete Post</a></li> -->
      </ul>
      <form class="form-inline my-2 my-lg-0">
        <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
      </form>
    </div>
   </nav>

    {% block body %}

    {% endblock %}

  </body>
</html>

Views/templates/index.html
{% extends "base.html" %}


<title>{% block title %}Home{% endblock %}</title>

<body>
  {% block body %}
    <div class="jumbotron">

      <h1>Welcome to the List of Posts Page!</h1>
        <ol>
          {% for post in posts_list %}
            <h2><li><a href="{{post.pk}}/">{{post.post_title}} </a></li></h2>
          {% endfor %}
        </ol>

    </div>
  {% endblock %}
</body>